#!/usr/bin/env bash
echo ""
echo "███████████████████████████████████████████████████████████"
echo "⚠️  PROXMOX COMMUNITY SCRIPTS INCOMPATIBLE WITH MONOREPO"
echo "███████████████████████████████████████████████████████████"
echo ""
echo "The community-scripts framework doesn't properly handle"
echo "pnpm monorepo workspaces. SparkyFitness requires:"
echo ""
echo "  ✓ Root-level dependency installation"
echo "  ✓ Monorepo-aware build process"  
echo "  ✓ Proper TypeScript resolution"
echo ""
echo "✨ SOLUTION: Use the STANDALONE installer instead:"
echo ""
echo "   bash -c \"\$(wget -qLO - https://raw.githubusercontent.com/C0NN0RAD0/SparkyFitness/main/instal#!/usr/bin/env bash
echo ""
echo "████████████████████████?reation"
echo "  • echo "onecho "⚠️  PROXMOX COMMUN"  • Proper monorepo dependency handling"
echo "  • Automated systemd service setup"
echo "  • Complete nginx configuration"
echo ""
echo "████echo "█████████████████████████████████████████████████████"
echo ""
